### Login
POST http://localhost:8080/login
Content-Type: application/json

{
    "accountNumber": "100001"
}

### Get account by account number

GET localhost:8080/account/100001

### Post transaction withdraw

POST localhost:8080/transaction/withdraw
Content-Type: application/json

{
    "accountNumber": "100001",
    "amount": 10
}
